env =  "dev" 
vpc_name =  "dev-ecs-workshop" 
alb_name =  "paresh-dev-alb" 
unique_name =  "paresh" 
cluster_name =  "asgard" 
instance_type =  "t3.micro" 
min_instances =  "1" 
max_instances =  "2" 
service_names = [ "odin" ]
service_contexts = [ "/odin" ]
service_health_checks = [ "/odin/actuator/health" ]
service_memories = [ "256" ]
service_cpus = [ "256" ]
docker_images = [ "738035286324.dkr.ecr.us-east-1.amazonaws.com/paresh/odin:910018cf7180157c4eef9ad27f08782b79ac3df2" ]
service_min_instances = [ "1" ]
service_max_instances = [ "3" ]